# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
permalink: /:year/:month/:day/:title.html
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Hawker Space  

description: 生活、好奇与探知
# gavatar头像及Favicon
#gavatar: http://pic.yupoo.com/24plus/E2O4V5oL/medium.jpg
#favicon: http://pic.yupoo.com/24plus/E2O4V5oL/medium.jpg

author:
  name: hawker
  email: hawkxiang.cpp@gmail.com
  github: hawkxiang
  twitter: szjoshua
  bio: Hawker's Technology Blog
#  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
